#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-api"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4a31ec14975b4e868e9b037de222b884" }
]

[assets]
directory = "./public"
